export const TEXTS = {
  HOME: 'Home',
  CATEGORIES: 'Categories',
  FAVOURITE: 'Favourite',
  YOUR_FAVOURITES: 'Your Favourites',
  MORE: 'More',
  DELIVERY_TO: 'Delivery To',
  TIME: 'Time',
  EDIT: 'Edit',
  DETAILS: 'Details',
  RECOMMENDED: 'Recommended',
  SEARCH_PRODUCTS_STORE: 'Search Products or Store',
  ADD_TO_CART: 'Add to cart',
  BUY_NOW: 'Buy Now',
  SHOPPING_CART: 'Shopping Cart',
  PROCEED_TO_CHECKOUT: 'Proceed  To checkout',
  NO_CART_ITEMS_FOUND: 'No items has added yet.',
  NO_FAV_ITEMS_FOUND: 'You have no favourite items.',
};
